# Generated by Django 5.2.1 on 2026-09-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('activity_type', models.CharField(choices=[('QUIZ', 'Quiz completion'), ('EXERCISE', 'Exercise completion'), ('FINAL_EXAM', 'Final exam completion'), ('PROFILE', 'Profile completion'), ('ADMIN_CUSTOM', 'Admin custom points'), ('CHALLENGE', 'Challenge')], max_length=50)),
                ('activity_id', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity_type', 'activity_id')},
            },
        ),
    ]
