# Generated by Django 5.2.1 on 2026-08-27 23:31

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='media/profile_pic/', verbose_name='Profile Picture')),
                ('cover_profile', models.ImageField(blank=True, upload_to='media/cover_profile/', verbose_name='cover_profile')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('find', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('members', 'Members'), ('friends', 'Friends and Family'), ('work', 'Manager & Co-worker'), ('other', 'Other')], max_length=9, verbose_name='How did you find us?')),
                ('educational_status', models.CharField(blank=True, choices=[('1', 'Student'), ('2', 'High School'), ('3', 'Bachelor'), ('4', 'Master'), ('5', 'PhD')], max_length=1, null=True, verbose_name='Educational status')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
