# Generated by Django 5.2.1 on 2026-09-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('AUTHENTICATIONS', 'Authentications'), ('COURSES', 'Courses'), ('POINTS', 'Points'), ('NOTIFICATIONS', 'Notifications'), ('PAYMENTS', 'Payment')], max_length=15)),
                ('call_function', models.CharField(max_length=255)),
                ('http_response_status_code', models.IntegerField()),
                ('log_datetime', models.DateTimeField(auto_now=True)),
                ('result', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
