# Generated by Django 5.2.1 on 2026-09-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('POINTS', 'Points Awarded'), ('EXERCISE', 'Exercise Status'), ('QUIZ', 'Quiz Result'), ('PROFILE', 'Profile Update'), ('EXAM', 'Final Exam Result'), ('ADMIN_NOTIFICATION', 'Admin Notification'), ('CHANGE_STATUS', 'Changes_status'), ('CHALLENGE', 'challenge')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('chapter_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('lesson_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('course_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('chapter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True)),
                ('course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
